### ISSUE TITLE
Suggestion: Possibly better collapse

### ISSUE THREAD

**Issue by IThordGray** [stringham/angular-template-formatter#1]
Hi there,

Possible suggestion for for better collapsing in VSCode (maybe as an option).

Instead of this;
```
              <i
                class="fa fa-ellipsis-h"
                aria-hidden="true"
              ></i> //notice the spacing here
```

// collapses to:
```
              <i ...
              ></i>
```

Rather have this;
```
              <i
                class="fa fa-ellipsis-h"
                aria-hidden="true"
                ></i> //notice the spacing here
```

// collapses to:
```           
               <i ...
```

**Comment by stringham** [comment]
I can't see your examples in this issue.

Use


    ```html
    <i
        class="foo"
        ...
    ```

When writing your issue for GitHub to render the coffee examples you have.

See https://guides.github.com/features/mastering-markdown/ for documentation of GitHub flavored markdown.

**Comment by IThordGray** [comment]
Sorry about that. Updated the issue to reflect properly

**Comment by stringham** [comment]
https://code.visualstudio.com/docs/editor/codebasics#_folding

> Since the 1.22 release, folding ranges can also be computed based on syntax tokens of the editor's configured language. The following languages already provide syntax aware folding:
> 
> Markdown, HTML, CSS, LESS, SCSS and JSON
> If you prefer to switch back to indentation based folding for one (or all) of the languages above, use:
> 
> ```
>   "[html]": {
>     "editor.foldingStrategy": "indentation"
>   },
> ```

I do not think this is an issue anymore.
