### ISSUE TITLE
Bug: Formatting deletes all nodes after special characters

### ISSUE THREAD

**Issue by casoetan** [stringham/angular-template-formatter#11]
@stringham When I try formatting a doc with a single curl brace, it breaks, deleting every node after the curly brace. See below

```html
<table>
    <tbody>
        <tr>
            <td>lorem ipsum</td>
        </tr>
        <tr>
            <td>{Critical}</td>
        </tr>
        <tr>
            <td>lorem ipsum</td>
        </tr>
        <tr>
            <td>lorem ipsum</td>
        </tr>
    </tbody>
</table>

```

I got 
```html
<table>
  <tbody>
    <tr>
      <td>lorem ipsum</td>
    </tr>
    <tr>
      <td></td>
    </tr>
  </tbody>
</table>
```

**Comment by casoetan** [comment]
@stringham any updates on this?

**Comment by stringham** [comment]
This extension leverages the Angular compiler. When I put your code into an angular app, it says:

>Unexpected character "EOF" (Do you have an unescaped "{" in your template? Use "{{ '{' }}") to escape it.) ("

it would be good for this extension to not format if there are parsing errors.

**Comment by casoetan** [comment]
@stringham that example does not seem to capture the issue properly.

Here is one that does not blow up in angular's compiler
```html
<span i18n="@@mandatoryType">
  {
    type, select,
    1 {Required}
    2 {Optional}
    3 {Don't Collect}
  }
</span>
```

but after formatting
```html
<span i18n="@@mandatoryType">
    1
</span>
```

https://angular.io/guide/i18n#select-among-alternative-text-messages

**Comment by casoetan** [comment]
@stringham were you able to look into this?

**Comment by stringham** [comment]
When I run it through Angular's parser being used for this extension, I get these errors:

```
"Unexpected character "EOF" (Do you have an unescaped "{" in your template? Use "{{ '{' }}") to escape it.)
Invalid ICU message. Missing '}'.
Invalid ICU message. Missing '}'."
```

Perhaps we need to update the version of Angular's template parser that we're using.

I just updated the extension to not format if there are parsing errors (https://github.com/stringham/angular-template-formatter/commit/7c3a9b20e25d730e1e50a66549fe0bf446489e08). Next step would be to see if upgrading the version of Angular's parser we're using would resolve your second issue.

Feel free to take a look at this if you want to.
