### ISSUE TITLE
Formatting suggestion

### ISSUE THREAD

**Issue by m4r71n85** [stringham/angular-template-formatter#2]
Hi,
Great job, anyway I have a suggestions. Can you add option where user can choose to leave the last bracket of an opening tag on the same line as the last attribute:
from:
                    <input
                        matInput
                        [matDatepicker]="picker"
                    >
to:
                    <input
                        matInput
                        [matDatepicker]="picker">

**Comment by sunnygb** [comment]
+1

**Comment by stringham** [comment]
You're welcome to open a pull request for this.

**Comment by larscom** [comment]
i was thinking the same thing! it would make this extension perfect :)
